name: JSON validate
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          find sensors schemas -name "*.json" -print0 | xargs -0 -I{} sh -c 'jq . "{}" >/dev/null'
